name: "Build & Deploy"

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run
        run: |
          echo "Hello, world!"
          echo "This is a sample workflow."
          echo "You can customize it as per your requirements."